"""Unitree sport API IDs.

This module defines numeric constants for the sport API identifiers and a mapping
`ROBOT_SPORT_API_IDS` that maps the string names (without the SPORT_API_ID_ prefix)
to their integer values. The mapping is intended to be consumed by other nodes
that reference APIs by name, for example:

    from sport_model import ROBOT_SPORT_API_IDS
    api_id = ROBOT_SPORT_API_IDS["BALANCESTAND"]

"""

# Numeric constants for API IDs (kept as upper case to be exported for anyone who
# needs numeric constants directly).
SPORT_API_ID_DAMP = 1001
SPORT_API_ID_BALANCESTAND = 1002
SPORT_API_ID_STOPMOVE = 1003
SPORT_API_ID_STANDUP = 1004
SPORT_API_ID_STANDDOWN = 1005
SPORT_API_ID_RECOVERYSTAND = 1006
SPORT_API_ID_EULER = 1007
SPORT_API_ID_MOVE = 1008
SPORT_API_ID_SIT = 1009
SPORT_API_ID_RISESIT = 1010
SPORT_API_ID_SPEEDLEVEL = 1015
SPORT_API_ID_HELLO = 1016
SPORT_API_ID_STRETCH = 1017
SPORT_API_ID_CONTENT = 1020
SPORT_API_ID_DANCE1 = 1022
SPORT_API_ID_DANCE2 = 1023
SPORT_API_ID_SWITCHJOYSTICK = 1027
SPORT_API_ID_POSE = 1028
SPORT_API_ID_SCRAPE = 1029
SPORT_API_ID_FRONTFLIP = 1030
SPORT_API_ID_FRONTJUMP = 1031
SPORT_API_ID_FRONTPOUNCE = 1032
SPORT_API_ID_HEART = 1036
SPORT_API_ID_STATICWALK = 1061
SPORT_API_ID_TROTRUN = 1062
SPORT_API_ID_ECONOMICGAIT = 1063
SPORT_API_ID_LEFTFLIP = 2041
SPORT_API_ID_BACKFLIP = 2043
SPORT_API_ID_HANDSTAND = 2044
SPORT_API_ID_FREEWALK = 2045
SPORT_API_ID_FREEBOUND = 2046
SPORT_API_ID_FREEJUMP = 2047
SPORT_API_ID_FREEAVOID = 2048
SPORT_API_ID_CLASSICWALK = 2049
SPORT_API_ID_WALKUPRIGHT = 2050
SPORT_API_ID_CROSSSTEP = 2051
SPORT_API_ID_AUTORECOVERY_SET = 2054
SPORT_API_ID_AUTORECOVERY_GET = 2055
SPORT_API_ID_SWITCHAVOIDMODE = 2058

# Mapping of short names to numeric IDs for easy lookups in other modules.
ROBOT_SPORT_API_IDS = {
    "DAMP": SPORT_API_ID_DAMP,
    "BALANCESTAND": SPORT_API_ID_BALANCESTAND,
    "STOPMOVE": SPORT_API_ID_STOPMOVE,
    "STANDUP": SPORT_API_ID_STANDUP,
    "STANDDOWN": SPORT_API_ID_STANDDOWN,
    "RECOVERYSTAND": SPORT_API_ID_RECOVERYSTAND,
    "EULER": SPORT_API_ID_EULER,
    "MOVE": SPORT_API_ID_MOVE,
    "SIT": SPORT_API_ID_SIT,
    "RISESIT": SPORT_API_ID_RISESIT,
    "SPEEDLEVEL": SPORT_API_ID_SPEEDLEVEL,
    "HELLO": SPORT_API_ID_HELLO,
    "STRETCH": SPORT_API_ID_STRETCH,
    "CONTENT": SPORT_API_ID_CONTENT,
    "DANCE1": SPORT_API_ID_DANCE1,
    "DANCE2": SPORT_API_ID_DANCE2,
    "SWITCHJOYSTICK": SPORT_API_ID_SWITCHJOYSTICK,
    "POSE": SPORT_API_ID_POSE,
    "SCRAPE": SPORT_API_ID_SCRAPE,
    "FRONTFLIP": SPORT_API_ID_FRONTFLIP,
    "FRONTJUMP": SPORT_API_ID_FRONTJUMP,
    "FRONTPOUNCE": SPORT_API_ID_FRONTPOUNCE,
    "HEART": SPORT_API_ID_HEART,
    "STATICWALK": SPORT_API_ID_STATICWALK,
    "TROTRUN": SPORT_API_ID_TROTRUN,
    "ECONOMICGAIT": SPORT_API_ID_ECONOMICGAIT,
    "LEFTFLIP": SPORT_API_ID_LEFTFLIP,
    "BACKFLIP": SPORT_API_ID_BACKFLIP,
    "HANDSTAND": SPORT_API_ID_HANDSTAND,
    "FREEWALK": SPORT_API_ID_FREEWALK,
    "FREEBOUND": SPORT_API_ID_FREEBOUND,
    "FREEJUMP": SPORT_API_ID_FREEJUMP,
    "FREEAVOID": SPORT_API_ID_FREEAVOID,
    "CLASSICWALK": SPORT_API_ID_CLASSICWALK,
    "WALKUPRIGHT": SPORT_API_ID_WALKUPRIGHT,
    "CROSSSTEP": SPORT_API_ID_CROSSSTEP,
    "AUTORECOVERY_SET": SPORT_API_ID_AUTORECOVERY_SET,
    "AUTORECOVERY_GET": SPORT_API_ID_AUTORECOVERY_GET,
    "SWITCHAVOIDMODE": SPORT_API_ID_SWITCHAVOIDMODE,
}

__all__ = [
    # constants
    "SPORT_API_ID_DAMP",
    "SPORT_API_ID_BALANCESTAND",
    "SPORT_API_ID_STOPMOVE",
    "SPORT_API_ID_STANDUP",
    "SPORT_API_ID_STANDDOWN",
    "SPORT_API_ID_RECOVERYSTAND",
    "SPORT_API_ID_EULER",
    "SPORT_API_ID_MOVE",
    "SPORT_API_ID_SIT",
    "SPORT_API_ID_RISESIT",
    "SPORT_API_ID_SPEEDLEVEL",
    "SPORT_API_ID_HELLO",
    "SPORT_API_ID_STRETCH",
    "SPORT_API_ID_CONTENT",
    "SPORT_API_ID_DANCE1",
    "SPORT_API_ID_DANCE2",
    "SPORT_API_ID_SWITCHJOYSTICK",
    "SPORT_API_ID_POSE",
    "SPORT_API_ID_SCRAPE",
    "SPORT_API_ID_FRONTFLIP",
    "SPORT_API_ID_FRONTJUMP",
    "SPORT_API_ID_FRONTPOUNCE",
    "SPORT_API_ID_HEART",
    "SPORT_API_ID_STATICWALK",
    "SPORT_API_ID_TROTRUN",
    "SPORT_API_ID_ECONOMICGAIT",
    "SPORT_API_ID_LEFTFLIP",
    "SPORT_API_ID_BACKFLIP",
    "SPORT_API_ID_HANDSTAND",
    "SPORT_API_ID_FREEWALK",
    "SPORT_API_ID_FREEBOUND",
    "SPORT_API_ID_FREEJUMP",
    "SPORT_API_ID_FREEAVOID",
    "SPORT_API_ID_CLASSICWALK",
    "SPORT_API_ID_WALKUPRIGHT",
    "SPORT_API_ID_CROSSSTEP",
    "SPORT_API_ID_AUTORECOVERY_SET",
    "SPORT_API_ID_AUTORECOVERY_GET",
    "SPORT_API_ID_SWITCHAVOIDMODE",
    # mapping
    "ROBOT_SPORT_API_IDS",
]
